# Dataset creation

Project title: Automating literature reviews using recommender systems


Authors : Alarmelu PM, Akhila Bolisetty, Andrew Szeto

The purpose of this file is to create the dataset for our cold start content-based filtering algorithm.
We take up rows of data as chunks from the arxiv dataset and make a dataset for our own analysis.

In [ ]:
import pandas as pd

In [28]:
chunk_size=5000
batch_no=1
for chunk in pd.read_csv('cs_DL.tsv', sep='\t',chunksize=chunk_size):
    chunk.to_csv('chunk'+str(batch_no)+'.csv',index=False)
    batch_no+=1

In [29]:
df1 = pd.read_csv('chunk1.csv')
df1.head()

,Unnamed: 0,abstract,acm_class,arxiv_id,author_text,categories,comments,created,doi,num_authors,num_categories,primary_cat,title,updated,categories_list
0,465653,The Microsoft TerraServer stores aerial and sa...,H.2.4;H.2.8;H.3.5,cs/9809011,"Tom Barclay, Robert Eberl, Jim Gray, John Nord...","cs.DB,cs.DL",Original file at\n http://research.microsoft....,1998-09-04,NaN,15,2,cs.DB,Microsoft TerraServer,NaN,"['cs.DB', 'cs.DL']"
1,893071,The World Wide Web is fast becoming a source o...,H.1.1,cs/9809025,"Bernardo A. Huberman, Lada A. Adamic","cs.MA,cs.DL",NaN,1998-09-17,NaN,2,2,cs.MA,Novelty and Social Search in the World Wide Web,NaN,"['cs.MA', 'cs.DL']"
2,1110692,The database research community is rightly pro...,H.0;H.2;H.3;H.4;H.5,cs/9811013,"Phil Bernstein, Michael Brodie, Stefano Ceri, ...","cs.DB,cs.DL",20 pages in HTML; an original in MSword at\n ...,1998-11-09,NaN,16,2,cs.DB,The Asilomar Report on Database Research,NaN,"['cs.DB', 'cs.DL']"
3,91255,This paper addresses the issue of making legac...,H.3.7,cs/9811020,"Elizabeth Anderson, Robert Atkinson, Cynthia C...",cs.DL,"21 pages, 5 figures",1998-11-11,NaN,5,1,cs.DL,Digitizing Legacy Documents: A Knowledge-Base ...,NaN,['cs.DL']
4,465232,This paper presents the design and the current...,H.3.7,cs/9812009,Fabio Crestani,cs.DL,NaN,1998-12-10,NaN,1,1,cs.DL,Vocal Access to a Newspaper Archive: Design Is...,NaN,['cs.DL']

In [30]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2664 entries, 0 to 2663
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       2664 non-null   int64
 1   abstract         2664 non-null   object
 2   acm_class        331 non-null    object
 3   arxiv_id         2664 non-null   object
 4   author_text      2664 non-null   object
 5   categories       2664 non-null   object
 6   comments         1825 non-null   object
 7   created          2664 non-null   object
 8   doi              840 non-null    object
 9   num_authors      2664 non-null   int64
 10  num_categories   2664 non-null   int64
 11  primary_cat      2664 non-null   object
 12  title            2664 non-null   object
 13  updated          684 non-null    object
 14  categories_list  2664 non-null   object
dtypes: int64(3), object(12)
memory usage: 312.3+ KB

In [31]:
df1.columns

Index(['Unnamed: 0', 'abstract', 'acm_class', 'arxiv_id', 'author_text',
       'categories', 'comments', 'created', 'doi', 'num_authors',
       'num_categories', 'primary_cat', 'title', 'updated', 'categories_list'],
      dtype='object')

In [32]:
chunk_size=5000
batch_no=2
for chunk in pd.read_csv('cs_DB.tsv', sep='\t',chunksize=chunk_size):
    chunk.to_csv('chunk'+str(batch_no)+'.csv',index=False)
    batch_no+=1

In [33]:
df2 = pd.read_csv('chunk2.csv')
df2.head()

,Unnamed: 0,abstract,acm_class,arxiv_id,author_text,categories,comments,created,doi,num_authors,num_categories,primary_cat,title,updated,categories_list
0,329549,NTsort is an external sort on WindowsNT 5.0. I...,D.5;H.2,cs/9809004,"Jim Gray, Joshua Coates, Chris Nyberg","cs.DB,cs.PF",Original word file at:\n http://research.micr...,1998-09-01,NaN,3,2,cs.DB,Performance / Price Sort,NaN,"['cs.DB', 'cs.PF']"
1,704923,Simple economic and performance arguments sugg...,H.3.4,cs/9809005,"Jim Gray, Goetz Graefe",cs.DB,Original document at:\n http://research.micro...,1998-09-01,NaN,2,1,cs.DB,"The Five-Minute Rule Ten Years Later, and Othe...",NaN,['cs.DB']
2,465653,The Microsoft TerraServer stores aerial and sa...,H.2.4;H.2.8;H.3.5,cs/9809011,"Tom Barclay, Robert Eberl, Jim Gray, John Nord...","cs.DB,cs.DL",Original file at\n http://research.microsoft....,1998-09-04,NaN,15,2,cs.DB,Microsoft TerraServer,NaN,"['cs.DB', 'cs.DL']"
3,1372704,We study a set of linear transformations on th...,H.2.2,cs/9809023,"Davood Rafiei, Alberto Mendelzon",cs.DB,NaN,1998-09-17,NaN,2,1,cs.DB,Similarity-Based Queries for Time Series Data,1998-09-18,['cs.DB']
4,269336,We propose an improvement of the known DFT-bas...,H.2;H.3,cs/9809033,"Davood Rafiei, Alberto Mendelzon",cs.DB,NaN,1998-09-18,NaN,2,1,cs.DB,Efficient Retrieval of Similar Time Sequences ...,1998-09-25,['cs.DB']

In [34]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4002 entries, 0 to 4001
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       4002 non-null   int64
 1   abstract         4002 non-null   object
 2   acm_class        675 non-null    object
 3   arxiv_id         4002 non-null   object
 4   author_text      4002 non-null   object
 5   categories       4002 non-null   object
 6   comments         2443 non-null   object
 7   created          4002 non-null   object
 8   doi              549 non-null    object
 9   num_authors      4002 non-null   int64
 10  num_categories   4002 non-null   int64
 11  primary_cat      4002 non-null   object
 12  title            4002 non-null   object
 13  updated          1037 non-null   object
 14  categories_list  4002 non-null   object
dtypes: int64(3), object(12)
memory usage: 469.1+ KB

In [35]:
import os, glob
path = "/Users/ushapraveen/Documents/MSBA/sem_4/BAN_693/SciencePaper_reco/Dataset_creation"

In [36]:
all_files = glob.glob(os.path.join(path, "chunk*.csv"))

In [37]:
all_files

['/Users/ushapraveen/Documents/MSBA/sem_4/BAN_693/SciencePaper_reco/Dataset_creation/chunk2.csv',
 '/Users/ushapraveen/Documents/MSBA/sem_4/BAN_693/SciencePaper_reco/Dataset_creation/chunk1.csv']

In [38]:
col_names=['Unnamed: 0', 'abstract', 'acm_class', 'author_text', 'categories',
           'comments', 'created', 'doi', 'num_authors', 'num_categories',
           'primary_cat', 'title', 'updated', 'categories_list']
df_merged = pd.DataFrame(index=range(10), columns=col_names)

In [39]:
import glob
files = glob.glob("/Users/ushapraveen/Documents/MSBA/sem_4/BAN_693/SciencePaper_reco/Dataset_creation/chunk*.csv")
dfs = [pd.read_csv(f, header=None, sep=",") for f in files]

science_papers = pd.concat(dfs,ignore_index=True)

In [40]:
science_papers

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Unnamed: 0,abstract,acm_class,arxiv_id,author_text,categories,comments,created,doi,num_authors,num_categories,primary_cat,title,updated,categories_list
1,329549,NTsort is an external sort on WindowsNT 5.0. I...,D.5;H.2,cs/9809004,"Jim Gray, Joshua Coates, Chris Nyberg","cs.DB,cs.PF",Original word file at:\n http://research.micr...,1998-09-01,NaN,3,2,cs.DB,Performance / Price Sort,NaN,"['cs.DB', 'cs.PF']"
2,704923,Simple economic and performance arguments sugg...,H.3.4,cs/9809005,"Jim Gray, Goetz Graefe",cs.DB,Original document at:\n http://research.micro...,1998-09-01,NaN,2,1,cs.DB,"The Five-Minute Rule Ten Years Later, and Othe...",NaN,['cs.DB']
3,465653,The Microsoft TerraServer stores aerial and sa...,H.2.4;H.2.8;H.3.5,cs/9809011,"Tom Barclay, Robert Eberl, Jim Gray, John Nord...","cs.DB,cs.DL",Original file at\n http://research.microsoft....,1998-09-04,NaN,15,2,cs.DB,Microsoft TerraServer,NaN,"['cs.DB', 'cs.DL']"
4,1372704,We study a set of linear transformations on th...,H.2.2,cs/9809023,"Davood Rafiei, Alberto Mendelzon",cs.DB,NaN,1998-09-17,NaN,2,1,cs.DB,Similarity-Based Queries for Time Series Data,1998-09-18,['cs.DB']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6663,586717,"Objective: Translational science aims at ""tran...",NaN,1812.10609,Qing Ke,"cs.DL,cs.CY,physics.soc-ph",Accepted at JAMIA; Supporting Information at\n...,2018-12-26,10.1093/jamia/ocy177,1,3,cs.DL,Identifying translational science through embe...,NaN,"['cs.DL', 'cs.CY', 'physics.soc-ph']"
6664,750271,A Wikipedia book (known as Wikibook) is a coll...,NaN,1812.10937,"Shahar Admati, Lior Rokach, Bracha Shapira","cs.DL,cs.IR,cs.LG",NaN,2018-12-28,NaN,3,3,cs.DL,Wikibook-Bot - Automatic Generation of a Wikip...,NaN,"['cs.DL', 'cs.IR', 'cs.LG']"
6665,1173063,"As science advances, the academic community ha...",NaN,1812.11252,"Haofeng Jia, Erik Saule","cs.IR,cs.DL,cs.SI",NaN,2018-12-28,NaN,2,3,cs.IR,Towards Finding Non-obvious Papers: An Analysi...,NaN,"['cs.IR', 'cs.DL', 'cs.SI']"
6666,357648,Mechanisms are a fundamental concept in many a...,NaN,1812.11431,Robert B Allen,cs.DL,NaN,2018-12-29,NaN,1,1,cs.DL,Issues for Using Semantic Modeling to Represen...,NaN,['cs.DL']
6667,1369244,Alternative metrics (aka altmetrics) are gaini...,NaN,1812.11813,"Andrea Giovanni Nuzzolese, Paolo Ciancarini, A...",cs.DL,NaN,2018-12-31,10.1007/s11192-018-2988-z,6,1,cs.DL,Do altmetrics work for assessing research qual...,NaN,['cs.DL']

In [41]:
science_papers.columns = science_papers.iloc[0]
science_papers = science_papers[1:]

In [42]:
science_papers

,Unnamed: 0,abstract,acm_class,arxiv_id,author_text,categories,comments,created,doi,num_authors,num_categories,primary_cat,title,updated,categories_list
1,329549,NTsort is an external sort on WindowsNT 5.0. I...,D.5;H.2,cs/9809004,"Jim Gray, Joshua Coates, Chris Nyberg","cs.DB,cs.PF",Original word file at:\n http://research.micr...,1998-09-01,NaN,3,2,cs.DB,Performance / Price Sort,NaN,"['cs.DB', 'cs.PF']"
2,704923,Simple economic and performance arguments sugg...,H.3.4,cs/9809005,"Jim Gray, Goetz Graefe",cs.DB,Original document at:\n http://research.micro...,1998-09-01,NaN,2,1,cs.DB,"The Five-Minute Rule Ten Years Later, and Othe...",NaN,['cs.DB']
3,465653,The Microsoft TerraServer stores aerial and sa...,H.2.4;H.2.8;H.3.5,cs/9809011,"Tom Barclay, Robert Eberl, Jim Gray, John Nord...","cs.DB,cs.DL",Original file at\n http://research.microsoft....,1998-09-04,NaN,15,2,cs.DB,Microsoft TerraServer,NaN,"['cs.DB', 'cs.DL']"
4,1372704,We study a set of linear transformations on th...,H.2.2,cs/9809023,"Davood Rafiei, Alberto Mendelzon",cs.DB,NaN,1998-09-17,NaN,2,1,cs.DB,Similarity-Based Queries for Time Series Data,1998-09-18,['cs.DB']
5,269336,We propose an improvement of the known DFT-bas...,H.2;H.3,cs/9809033,"Davood Rafiei, Alberto Mendelzon",cs.DB,NaN,1998-09-18,NaN,2,1,cs.DB,Efficient Retrieval of Similar Time Sequences ...,1998-09-25,['cs.DB']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6663,586717,"Objective: Translational science aims at ""tran...",NaN,1812.10609,Qing Ke,"cs.DL,cs.CY,physics.soc-ph",Accepted at JAMIA; Supporting Information at\n...,2018-12-26,10.1093/jamia/ocy177,1,3,cs.DL,Identifying translational science through embe...,NaN,"['cs.DL', 'cs.CY', 'physics.soc-ph']"
6664,750271,A Wikipedia book (known as Wikibook) is a coll...,NaN,1812.10937,"Shahar Admati, Lior Rokach, Bracha Shapira","cs.DL,cs.IR,cs.LG",NaN,2018-12-28,NaN,3,3,cs.DL,Wikibook-Bot - Automatic Generation of a Wikip...,NaN,"['cs.DL', 'cs.IR', 'cs.LG']"
6665,1173063,"As science advances, the academic community ha...",NaN,1812.11252,"Haofeng Jia, Erik Saule","cs.IR,cs.DL,cs.SI",NaN,2018-12-28,NaN,2,3,cs.IR,Towards Finding Non-obvious Papers: An Analysi...,NaN,"['cs.IR', 'cs.DL', 'cs.SI']"
6666,357648,Mechanisms are a fundamental concept in many a...,NaN,1812.11431,Robert B Allen,cs.DL,NaN,2018-12-29,NaN,1,1,cs.DL,Issues for Using Semantic Modeling to Represen...,NaN,['cs.DL']
6667,1369244,Alternative metrics (aka altmetrics) are gaini...,NaN,1812.11813,"Andrea Giovanni Nuzzolese, Paolo Ciancarini, A...",cs.DL,NaN,2018-12-31,10.1007/s11192-018-2988-z,6,1,cs.DL,Do altmetrics work for assessing research qual...,NaN,['cs.DL']

In [43]:
science_papers.to_csv('science_papers.csv') # dataset for the content based filtering